# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
        v.name = "App_Server"
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.37.10"
  config.vm.synced_folder "synced/", "/vagrant_synced"
  config.ssh.insert_key = true
  config.vm.provision "shell", path: "provision.sh"
end
