# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/xenial64"
	config.ssh.insert_key = true

	config.vm.provision "shell", path: "provision.sh"
	config.vm.synced_folder "synced/", "/vagrant_synced"

	config.vm.define "Webserver_1" do |web|
		web.vm.network "private_network", ip: "192.168.34.10"
		web.vm.provider "virtualbox" do |v|
        	v.name = "Webserver_1"
  		end
  	end

  	config.vm.define "Webserver_2" do |web|
    	web.vm.network "private_network", ip: "192.168.34.11"
    	web.vm.provider "virtualbox" do |v|
        	v.name = "Webserver_2"
  		end
  	end

end